apiVersion: v1
kind: Secret
metadata:
  name: garage-secret
  namespace: garage
type: Opaque
data:
  rpc_secret: MGFiZWI1ZjQxMzMzZmNjOTU3ZGUyMGRjZGFlYjJiODA5ZmQ1ZmI3Y2I2MGNlZDI1YzA5NDJkOGUzZjU2YmQ2ZA==
  admin_token: ak9kOGp5eExTYnJnandON001OXBhS0l2TmtlS2ZoNlhWcEpvbXZoUW5jcWQ1M3lFU2tvWHc5dlhJMTVqUFJKaw==
