apiVersion: core.pointblank.com/v1alpha1
kind: Backup
metadata:
  name: vaultwarden-prod-backup
  namespace: vaultwarden
spec:
  # The name of the application being backed up (used for logs and namespacing)
  targetApp: "vaultwarden"
  databaseType: sqlite
  # The source PVC that contains the live data you want to back up
  sourcePVCName: "vaultwarden-pvc"

  # Where the source PVC will be mounted inside the backup runner pod
  mountPath: "/data"

  schedule: "*/10 * * * *"

  # Optional: Let the operator auto-generate the bucket name (<name>-backups)
  # Or explicitly specify it here:
  bucketName: "vaultwarden-vault"

  # Data retention policy (automatically prunes files older than 7 days)
  retentionDays: 7

  # By leaving 'credentialsSecret' and 'endpoint' omitted or empty, 
  # your operator dynamically discovers the Garage service and provisions everything!
