apiVersion: v1
kind: Secret
metadata:
  name: atlas-production-db-creds
  namespace: garage
type: Opaque
stringData:
  # IMPORTANT: Replace 'REPLACE_WITH_YOUR_ACTUAL_PASSWORD' with your actual database user password.
  # If your password has special characters like @, :, or /, make sure they are URL-encoded!
  connection-string: "mongodb+srv://aneeshhegde7110_db_user:3oed13rGTCTN2OqV@cluster0.6zdlzr1.mongodb.net"
---
apiVersion: core.pointblank.com/v1alpha1
kind: Backup
metadata:
  name: cloud-atlas-prod-backup
  namespace: default
spec:
  targetApp: atlas-cloud-cluster
  databaseType: mongodb-atlas  # Instructs the controller to look up your new blueprint
  schedule: "0 0 * * *"         # Triggers every single midnight (runs in Asia/Kolkata timezone)
  retentionDays: 14            # Automatically prunes old backups from Garage S3 after 2 weeks
  databaseEnv:
    - name: ATLAS_URI
      valueFrom:
        secretKeyRef:
          name: atlas-production-db-creds
          key: connection-string
